CREATE TABLE DOI(book_id VARCHAR(20), title VARCHAR(30), DOI DATE, DOR DATE);
INSERT INTO bookpeople (username, user_id, address, phone_number, email, book_id) VALUES ('vedantjadhav', '101', 'Treasure Park', '9386265934', 'vedant.jadhav20@vit.edu', 'b101' );
INSERT INTO bookpeople (username, user_id, address, phone_number, email, book_id) VALUES ('nikki', '102', 'Lake Vista', '9386265935', 'nikita.shitole20@vit.edu', 'b102' );
INSERT INTO bookpeople (username, user_id, address, phone_number, email, book_id) VALUES ('soham', '103', 'Nashik', '9386265936', 'soham.shirsat20@vit.edu', 'b10' );
INSERT INTO bookpeople (username, user_id, address, phone_number, email, book_id) VALUES ('jagtap', '104', 'Viman Nagar', '9386265937', 'vedant.jagtap20@vit.edu', 'b10' );
DELETE FROM bookpeople WHERE age = 'NULL';
DELETE FROM bookpeople WHERE age IS NULL;
ALTER TABLE bookpeople ADD (gender VARCHAR(10));
ALTER TABLE bookpeople ADD (branch VARCHAR(10));
UPDATE bookpeople SET gender = 'male', branch = 'CS', username = 'jadhav' WHERE user_id = '101';
UPDATE bookpeople SET gender = 'male', branch = 'CS' WHERE user_id = '103';
UPDATE bookpeople SET gender = 'male', branch = 'CS' WHERE user_id = '104';
UPDATE bookpeople SET branch = 'CS' WHERE user_id = '102';
INSERT INTO book VALUES('b101', 'Angels and demons', 'Dan Brown', 10, 500);
INSERT INTO book VALUES('b102', 'The One', 'John Marrs', 5, 350);
INSERT INTO book VALUES('b103', 'Bridge of Clay', 'Mark Zusak', 20, 470);
INSERT INTO book VALUES('b104', 'Hopeless', 'Colleen Hoover', 12, 320);
INSERT INTO book VALUES('b105', 'More Than This', 'Patrick Ness', 7, 200);
INSERT INTO book VALUES('b106', 'The Song of Achilles', 'Madeline Miller', 23, 450);
INSERT INTO book VALUES('b107', 'The Silent Patient', 'Alex Michaelides', 40, 570);
INSERT INTO book VALUES('b108', 'We Were Liars', 'E. Lockhart', 35, 580);
INSERT INTO book VALUES('b109', 'Lovely Bones', 'Alice Sebold', 15, 420);
INSERT INTO book VALUES('b10', 'Looking for Alaska', 'John Green', 40, 370);
ALTER TABLE book MODIFY(title VARCHAR(40));
ALTER TABLE book MODIFY(book_id VARCHAR(10));
select * from bookpeople;
select * from bookpeople ORDER BY user_id asc;
UPDATE bookpeople SET phone_number = '8275917503', user_id = 18 WHERE book_id = 'b118';
UPDATE bookpeople SET phone_number = '9589285729', user_id = 119 WHERE book_id = 'b119';
select * from bookpeople;
UPDATE bookpeople SET user_id = 118 WHERE book_id = 'b118';
UPDATE bookpeople SET user_id = 120 WHERE book_id = 'b120';
update bookpeople SET date_of_joining = (TO_DATE('17/12/2015', 'DD/MM/YYYY')) WHERE user_id = 101;
update bookpeople SET date_of_joining = (TO_DATE('14/01/2014', 'DD/MM/YYYY')) WHERE user_id = 102;
update bookpeople SET date_of_joining = (TO_DATE('24/06/2018', 'DD/MM/YYYY')) WHERE user_id = 103;
update bookpeople SET date_of_joining = (TO_DATE('13/09/2012', 'DD/MM/YYYY')) WHERE user_id = 104;
update bookpeople SET date_of_joining = (TO_DATE('09/11/2018', 'DD/MM/YYYY')) WHERE user_id = 105;
update bookpeople SET date_of_joining = (TO_DATE('11/02/2021', 'DD/MM/YYYY')) WHERE user_id = 106;
update bookpeople SET date_of_joining = (TO_DATE('18/04/2016', 'DD/MM/YYYY')) WHERE user_id = 107;
update bookpeople SET date_of_joining = (TO_DATE('29/02/2012', 'DD/MM/YYYY')) WHERE user_id = 108;
update bookpeople SET date_of_joining = (TO_DATE('01/10/2019', 'DD/MM/YYYY')) WHERE user_id = 109;
update bookpeople SET date_of_joining = (TO_DATE('20/12/2020', 'DD/MM/YYYY')) WHERE user_id = 110;
update bookpeople SET date_of_joining = (TO_DATE('30/07/2015', 'DD/MM/YYYY')) WHERE user_id = 111;
update bookpeople SET date_of_joining = (TO_DATE('04/05/2016', 'DD/MM/YYYY')) WHERE user_id = 112;
update bookpeople SET date_of_joining = (TO_DATE('20/01/2015', 'DD/MM/YYYY')) WHERE user_id = 113;
update bookpeople SET date_of_joining = (TO_DATE('15/03/2020', 'DD/MM/YYYY')) WHERE user_id = 114;
update bookpeople SET date_of_joining = (TO_DATE('27/06/2018', 'DD/MM/YYYY')) WHERE user_id = 115;
update bookpeople SET date_of_joining = (TO_DATE('13/12/2021', 'DD/MM/YYYY')) WHERE user_id = 116;
update bookpeople SET date_of_joining = (TO_DATE('19/10/2013', 'DD/MM/YYYY')) WHERE user_id = 117;
update bookpeople SET date_of_joining = (TO_DATE('07/02/2017', 'DD/MM/YYYY')) WHERE user_id = 118;
update bookpeople SET date_of_joining = (TO_DATE('22/03/2014', 'DD/MM/YYYY')) WHERE user_id = 119;
update bookpeople SET date_of_joining = (TO_DATE('14/10/2019', 'DD/MM/YYYY')) WHERE user_id = 120;
ALTER TABLE bookpeople RENAME COLUMN date_of_joining TO joining_date;
select * from bookpeople;
select * from bookpeople where age>20;
select * from bookpeople where age<20 and branch = 'CS';
select * from bookpeople where address not in ('Bibvewadi');
select * from bookpeople where book_id between 'b106' and 'b115';
update bookpeople SET email = NULL WHERE user_id = 111;
update bookpeople SET email = NULL WHERE user_id = 116;
update bookpeople SET email = NULL WHERE user_id = 107;
update bookpeople SET email = NULL WHERE user_id = 118;
select * from bookpeople where email is null;
select * from bookpeople where address like 'N%';
select * from bookpeople where address like '%i';
select * from bookpeople where address like '%a%' ORDER BY user_id asc;
 select * from bookpeople where address not like '%e' ORDER BY user_id asc; 
select * from bookpeople order by user_id asc;
select age, count(*) from bookpeople group by age order by age asc;
select branch, count(*) from bookpeople group by branch order by count(*) asc; 



