CREATE TABLE DOI(book_id VARCHAR(20), title VARCHAR(30), DOI DATE, DOR DATE);
INSERT INTO bookpeople (username, user_id, address, phone_number, email, book_id) VALUES ('vedantjadhav', '101', 'Treasure Park', '9386265934', 'vedant.jadhav20@vit.edu', 'b101' );
INSERT INTO bookpeople (username, user_id, address, phone_number, email, book_id) VALUES ('nikki', '102', 'Lake Vista', '9386265935', 'nikita.shitole20@vit.edu', 'b102' );
INSERT INTO bookpeople (username, user_id, address, phone_number, email, book_id) VALUES ('soham', '103', 'Nashik', '9386265936', 'soham.shirsat20@vit.edu', 'b10' );
INSERT INTO bookpeople (username, user_id, address, phone_number, email, book_id) VALUES ('jagtap', '104', 'Viman Nagar', '9386265937', 'vedant.jagtap20@vit.edu', 'b10' );
DELETE FROM bookpeople WHERE age = 'NULL';
DELETE FROM bookpeople WHERE age IS NULL;
ALTER TABLE bookpeople ADD (gender VARCHAR(10));
ALTER TABLE bookpeople ADD (branch VARCHAR(10));
UPDATE bookpeople SET gender = 'male', branch = 'CS', username = 'jadhav' WHERE user_id = '101';
UPDATE bookpeople SET gender = 'male', branch = 'CS' WHERE user_id = '103';
UPDATE bookpeople SET gender = 'male', branch = 'CS' WHERE user_id = '104';
UPDATE bookpeople SET branch = 'CS' WHERE user_id = '102';
INSERT INTO book VALUES('b101', 'Angels and demons', 'Dan Brown', 10, 500);
INSERT INTO book VALUES('b102', 'The One', 'John Marrs', 5, 350);
INSERT INTO book VALUES('b103', 'Bridge of Clay', 'Mark Zusak', 20, 470);
INSERT INTO book VALUES('b104', 'Hopeless', 'Colleen Hoover', 12, 320);
INSERT INTO book VALUES('b105', 'More Than This', 'Patrick Ness', 7, 200);
INSERT INTO book VALUES('b106', 'The Song of Achilles', 'Madeline Miller', 23, 450);
INSERT INTO book VALUES('b107', 'The Silent Patient', 'Alex Michaelides', 40, 570);
INSERT INTO book VALUES('b108', 'We Were Liars', 'E. Lockhart', 35, 580);
INSERT INTO book VALUES('b109', 'Lovely Bones', 'Alice Sebold', 15, 420);
INSERT INTO book VALUES('b10', 'Looking for Alaska', 'John Green', 40, 370);
ALTER TABLE book MODIFY(title VARCHAR(40));
ALTER TABLE book MODIFY(book_id VARCHAR(10));
select * from bookpeople;
select * from bookpeople ORDER BY user_id asc;
UPDATE bookpeople SET phone_number = '8275917503', user_id = 18 WHERE book_id = 'b118';
UPDATE bookpeople SET phone_number = '9589285729', user_id = 119 WHERE book_id = 'b119';
select * from bookpeople;
UPDATE bookpeople SET user_id = 118 WHERE book_id = 'b118';
UPDATE bookpeople SET user_id = 120 WHERE book_id = 'b120';
update bookpeople SET date_of_joining = (TO_DATE('17/12/2015', 'DD/MM/YYYY')) WHERE user_id = 101;
update bookpeople SET date_of_joining = (TO_DATE('14/01/2014', 'DD/MM/YYYY')) WHERE user_id = 102;
update bookpeople SET date_of_joining = (TO_DATE('24/06/2018', 'DD/MM/YYYY')) WHERE user_id = 103;
update bookpeople SET date_of_joining = (TO_DATE('13/09/2012', 'DD/MM/YYYY')) WHERE user_id = 104;
update bookpeople SET date_of_joining = (TO_DATE('09/11/2018', 'DD/MM/YYYY')) WHERE user_id = 105;
update bookpeople SET date_of_joining = (TO_DATE('11/02/2021', 'DD/MM/YYYY')) WHERE user_id = 106;
update bookpeople SET date_of_joining = (TO_DATE('18/04/2016', 'DD/MM/YYYY')) WHERE user_id = 107;
update bookpeople SET date_of_joining = (TO_DATE('29/02/2012', 'DD/MM/YYYY')) WHERE user_id = 108;
update bookpeople SET date_of_joining = (TO_DATE('01/10/2019', 'DD/MM/YYYY')) WHERE user_id = 109;
update bookpeople SET date_of_joining = (TO_DATE('20/12/2020', 'DD/MM/YYYY')) WHERE user_id = 110;
update bookpeople SET date_of_joining = (TO_DATE('30/07/2015', 'DD/MM/YYYY')) WHERE user_id = 111;
update bookpeople SET date_of_joining = (TO_DATE('04/05/2016', 'DD/MM/YYYY')) WHERE user_id = 112;
update bookpeople SET date_of_joining = (TO_DATE('20/01/2015', 'DD/MM/YYYY')) WHERE user_id = 113;
update bookpeople SET date_of_joining = (TO_DATE('15/03/2020', 'DD/MM/YYYY')) WHERE user_id = 114;
update bookpeople SET date_of_joining = (TO_DATE('27/06/2018', 'DD/MM/YYYY')) WHERE user_id = 115;
update bookpeople SET date_of_joining = (TO_DATE('13/12/2021', 'DD/MM/YYYY')) WHERE user_id = 116;
update bookpeople SET date_of_joining = (TO_DATE('19/10/2013', 'DD/MM/YYYY')) WHERE user_id = 117;
update bookpeople SET date_of_joining = (TO_DATE('07/02/2017', 'DD/MM/YYYY')) WHERE user_id = 118;
update bookpeople SET date_of_joining = (TO_DATE('22/03/2014', 'DD/MM/YYYY')) WHERE user_id = 119;
update bookpeople SET date_of_joining = (TO_DATE('14/10/2019', 'DD/MM/YYYY')) WHERE user_id = 120;
ALTER TABLE bookpeople RENAME COLUMN date_of_joining TO joining_date;
select * from bookpeople;
select * from bookpeople where age>20;
select * from bookpeople where age<20 and branch = 'CS';
select * from bookpeople where address not in ('Bibvewadi');
select * from bookpeople where book_id between 'b106' and 'b115';
update bookpeople SET email = NULL WHERE user_id = 111;
update bookpeople SET email = NULL WHERE user_id = 116;
update bookpeople SET email = NULL WHERE user_id = 107;
update bookpeople SET email = NULL WHERE user_id = 118;
select * from bookpeople where email is null;
select * from bookpeople where address like 'N%';
select * from bookpeople where address like '%i';
select * from bookpeople where address like '%a%' ORDER BY user_id asc;
 select * from bookpeople where address not like '%e' ORDER BY user_id asc; 
select * from bookpeople order by user_id asc;
select age, count(*) from bookpeople group by age order by age asc;
select branch, count(*) from bookpeople group by branch order by count(*) asc;
SELECT username, round(months_between(joining_date, Sysdate)) from bookpeople order by joining_date asc;
SELECT joining_date, add_months(joining_date, 2) from bookpeople;
select next_day(sysdate,'Monday') from dual;
select next_day('02-DEC-2021','Wednesday') from dual;
select last_day(sysdate) from dual;
SELECT TO_CHAR(sysdate, 'DAY') from dual;
SELECT CURRENT_DATE, CURRENT_TIMESTAMP, DBTIMEZONE,SESSIONTIMEZONE FROM DUAL;
select to_char(21) from dual;
select to_char(1234,'$9999') from dual;
select to_char(1234,'9999') from dual;
select to_char(1234.87,'$9999.99') from dual; 
select to_char(1234,'$9999,99') from dual; 
select username, email, nvl(email,'empty') from bookpeople order by user_id asc;
select username, email, nvl2(email, 0, 1) from bookpeople order by user_id asc;
CASE branch WHEN 'CS' THEN user_id-0.5 WHEN 'BBA' THEN user_id-1 WHEN 'Data Science' THEN age-2
ELSE age END Revised_age from bookpeople;
SELECT username, gender, user_id, DECODE(gender, 'male', user_id+1, 'female', user_id+2) revised_user_id FROM bookpeople order by user_id asc; 
SELECT username, age, CASE WHEN age<21 THEN 'underage' WHEN age>=21 THEN 'adult' ELSE 'not known' END AS age_text FROM bookpeople order by user_id asc;
SELECT NULLIF ('Helloworld', 'helloworld') FROM DUAL;
SELECT username, address, branch, NULLIF (length(address), length(branch)) nullif from bookpeople order by user_id asc;
SELECT COALESCE (email, branch) from bookpeople order by user_id asc;
SELECT username, UPPER(branch) from bookpeople order by user_id asc;
select username, INITCAP(branch) from bookpeople order by user_id asc;
UPDATE bookpeople SET gender = 'male' WHERE username = 'Jagtap';
select * from bookpeople order by user_id ;
UPDATE bookpeople SET username = 'Jadhav' WHERE user_id = 101;
UPDATE bookpeople SET username = 'Nikita' WHERE user_id = 102;
UPDATE bookpeople SET username = 'Soham' WHERE user_id = 103;
UPDATE bookpeople SET username = 'Jagtap' WHERE user_id = 104;
UPDATE bookpeople SET address = 'Wanowrie' WHERE user_id = 117;
UPDATE bookpeople SET user_id = '106' WHERE username = 'Sakshi';
UPDATE bookpeople SET branch = 'Business' WHERE username = 'Jadhav';
UPDATE bookpeople SET branch = 'Business' WHERE username = 'Vedant';
UPDATE bookpeople SET branch = 'Business' WHERE username = 'Aryan';
UPDATE bookpeople SET branch = 'LLB' WHERE username = 'Soham';
UPDATE bookpeople SET branch = 'LLB' WHERE username = 'Maitreyee';
UPDATE bookpeople SET branch = 'MBBS' WHERE username = 'Ishita';
UPDATE bookpeople SET branch = 'Architecture' WHERE username = 'Vanshika';
select * from bookpeople order by user_id ;
UPDATE bookpeople SET branch = 'Architecture' WHERE username = 'Rohan';
UPDATE bookpeople SET branch = 'MBBS' WHERE username = 'Rakshit';
UPDATE bookpeople SET branch = 'MBBS' WHERE username = 'Sakshi';
select branch, count(*) from bookpeople group by branch;
UPDATE bookpeople SET branch = 'Architecture' WHERE username = 'Vritika';
UPDATE bookpeople SET branch = 'IT' WHERE username = 'Sakshi';
UPDATE bookpeople SET branch = 'Mechanical' WHERE username = 'Tanishka';
UPDATE bookpeople SET branch = 'Mechanical' WHERE username = 'Rakshit';
UPDATE bookpeople SET branch = 'CS', username = 'Saniya' WHERE user_id = 115;
select address, count(*) from bookpeople group by address;
select * from bookpeople order by user_id ;
UPDATE bookpeople SET address = 'Bibvewadi' WHERE username = 'Jadhav';
UPDATE bookpeople SET address = 'Bibvewadi' WHERE username = 'Aarya';
UPDATE bookpeople SET address = 'Koregaon Park' WHERE username = 'Jagtap';
UPDATE bookpeople SET address = 'Katraj' WHERE username = 'Nikita';
UPDATE bookpeople SET address = 'Kothrud' WHERE username = 'Soham';
select address, count(*) from bookpeople group by address;
UPDATE bookpeople SET address = 'Baner' WHERE username = 'Sarakshie';
UPDATE bookpeople SET address = 'Bibvewadi' WHERE username = 'Vedant';
UPDATE bookpeople SET address = 'Bibvewadi' WHERE username = 'Vritika';
UPDATE bookpeople SET address = 'Kothrud' WHERE username = 'Sakshi';
UPDATE bookpeople SET address = 'Koregaon Park' WHERE username = 'Saharsh';
UPDATE bookpeople SET address = 'Koregaon Park' WHERE username = 'Saniya';
UPDATE bookpeople SET address = 'Kondhwa' WHERE username = 'Jay';
UPDATE bookpeople SET address = 'Kondhwa' WHERE username = 'Aryan';
UPDATE bookpeople SET address = 'Kondhwa' WHERE username = 'Ameya';
UPDATE bookpeople SET gender = 'male' WHERE username = 'Rakshit';
UPDATE bookpeople SET email = NULL WHERE username = 'Soham';
select * from book;
UPDATE book set book_id = 'b110' where price = 370;
UPDATE book SET price = 570 WHERE book_id = 'b103';
UPDATE book SET price = 200 WHERE book_id = 'b102';
select price, count(*) from book group by price;
UPDATE book SET price = 530 WHERE book_id = 'b108';
UPDATE book SET price = 530 WHERE book_id = 'b107';
UPDATE book SET price = 530 WHERE book_id = 'b103';
UPDATE book SET price = 350 WHERE book_id = 'b105';
UPDATE book SET price = 449.28 WHERE book_id = 'b101';
UPDATE book SET price = 449.28 WHERE book_id = 'b106';
UPDATE book SET price = 369.50 WHERE book_id = 'b104';
UPDATE book SET price = 369.50 WHERE book_id = 'b109';
UPDATE book SET price = 369.50 WHERE book_id = 'b110';
UPDATE bookpeople SET book_id = 'b107' WHERE username = 'Nikita';
UPDATE bookpeople SET book_id = 'b107' WHERE username = 'Aarya';
UPDATE bookpeople SET book_id = 'b107' WHERE username = 'Vedant';
UPDATE bookpeople SET book_id = 'b104' WHERE user_id = 101;
UPDATE bookpeople SET book_id = 'b102' WHERE user_id = 103;
UPDATE bookpeople SET book_id = 'b109' WHERE user_id = 104;
UPDATE bookpeople SET book_id = 'b107' WHERE user_id = 105;
UPDATE bookpeople SET book_id = 'b109' WHERE user_id = 106;
UPDATE bookpeople SET book_id = 'b103' WHERE user_id = 107;
UPDATE bookpeople SET book_id = 'b105' WHERE user_id = 108;
UPDATE bookpeople SET book_id = 'b104' WHERE user_id = 109;
UPDATE bookpeople SET book_id = 'b107' WHERE user_id = 110;
UPDATE bookpeople SET book_id = 'b102' WHERE user_id = 111;
UPDATE bookpeople SET book_id = 'b106' WHERE user_id = 112;
UPDATE bookpeople SET book_id = 'b103' WHERE user_id = 113;
UPDATE bookpeople SET book_id = 'b101' WHERE user_id = 114;
UPDATE bookpeople SET book_id = 'b108' WHERE user_id = 115;
UPDATE bookpeople SET book_id = 'b106' WHERE user_id = 116;
UPDATE bookpeople SET book_id = 'b105' WHERE user_id = 117;
UPDATE bookpeople SET book_id = 'b103' WHERE user_id = 118;
UPDATE bookpeople SET book_id = 'b107' WHERE user_id = 119;
UPDATE bookpeople SET book_id = 'b101' WHERE user_id = 120;
select book_id, count(*) from bookpeople group by book_id order by book_id;
ALTER TABLE DOI add (user_id VARCHAR(10));
INSERT INTO DOI VALUES('b104', 'Hopeless', TO_DATE('22/02/2016', 'DD/MM/YYYY'), TO_DATE('15/06/2016', 'DD/MM/YYYY'), 101);
select * from DOI;
INSERT INTO DOI VALUES('b107', 'The Silent Patient', TO_DATE('14/01/2014', 'DD/MM/YYYY'), TO_DATE('30/01/2014', 'DD/MM/YYYY'), 102);
INSERT INTO DOI VALUES('b102', 'The One', TO_DATE('30/07/2014', 'DD/MM/YYYY'), TO_DATE('20/08/2014', 'DD/MM/YYYY'), 103);
INSERT INTO DOI VALUES('b109', 'Lovely Bones', TO_DATE('13/10/2012', 'DD/MM/YYYY'), TO_DATE('22/08/2013', 'DD/MM/YYYY'), 104);
INSERT INTO DOI VALUES('b107', 'The Silent Patient', TO_DATE('01/12/2018', 'DD/MM/YYYY'), TO_DATE('31/12/2018', 'DD/MM/YYYY'), 105);
INSERT INTO DOI VALUES('b109', 'Lovely Bones', TO_DATE('20/02/2021', 'DD/MM/YYYY'), TO_DATE('20/07/2021', 'DD/MM/YYYY'), 106);
INSERT INTO DOI VALUES('b103', 'Bridge of Clay', TO_DATE('23/04/2016', 'DD/MM/YYYY'), TO_DATE('16/06/2016', 'DD/MM/YYYY'), 107);
INSERT INTO DOI VALUES('b105', 'More Than This', TO_DATE('15/06/2012', 'DD/MM/YYYY'), TO_DATE('23/07/2012', 'DD/MM/YYYY'), 108);
INSERT INTO DOI VALUES('b104', 'Hopeless', TO_DATE('01/01/2019', 'DD/MM/YYYY'), TO_DATE('03/03/2019', 'DD/MM/YYYY'), 109);
INSERT INTO DOI VALUES('b107', 'The Silent Patient', TO_DATE('07/02/2020', 'DD/MM/YYYY'), TO_DATE('01/08/2020', 'DD/MM/YYYY'), 110);
INSERT INTO DOI VALUES('b102', 'The One', TO_DATE('03/09/2015', 'DD/MM/YYYY'), TO_DATE('31/12/2015', 'DD/MM/YYYY'), 111);
INSERT INTO DOI VALUES('b106', 'The Song of Achilles', TO_DATE('22/05/2016', 'DD/MM/YYYY'), TO_DATE('15/06/2016', 'DD/MM/YYYY'), 112);
INSERT INTO DOI VALUES('b110', 'Looking for Alaska', TO_DATE('01/02/2015', 'DD/MM/YYYY'), TO_DATE('05/05/2015', 'DD/MM/YYYY'), 113);
INSERT INTO DOI VALUES('b101', 'Angels and demons', TO_DATE('25/03/2020', 'DD/MM/YYYY'), TO_DATE('24/05/2020', 'DD/MM/YYYY'), 114);
INSERT INTO DOI VALUES('b108', 'We Were Liars', TO_DATE('01/08/2018', 'DD/MM/YYYY'), TO_DATE('29/01/2019', 'DD/MM/YYYY'), 115);
INSERT INTO DOI VALUES('b106', 'The Song of Achilles', TO_DATE('19/03/2016', 'DD/MM/YYYY'), TO_DATE('16/09/2016', 'DD/MM/YYYY'), 116);
INSERT INTO DOI VALUES('b105', 'More Than This', TO_DATE('30/10/2013', 'DD/MM/YYYY'), TO_DATE('25/12/2013', 'DD/MM/YYYY'), 117);
INSERT INTO DOI VALUES('b103', 'Bridge of Clay', TO_DATE('07/03/2017', 'DD/MM/YYYY'), TO_DATE('13/07/2017', 'DD/MM/YYYY'), 118);
INSERT INTO DOI VALUES('b107', 'The Silent Patient', TO_DATE('30/06/2014', 'DD/MM/YYYY'), TO_DATE('19/10/2014', 'DD/MM/YYYY'), 119);
INSERT INTO DOI VALUES('b101', 'Angels and demons', TO_DATE('01/10/2019', 'DD/MM/YYYY'), TO_DATE('01/10/2019', 'DD/MM/YYYY'), 120);
SELECT * FROM DOI order by user_id;
ALTER TABLE DOI ADD (username VARCHAR(30));
UPDATE DOI SET username = 'Jadhav' WHERE user_id = '101';
UPDATE DOI SET username = 'Nikita' WHERE user_id = '102';
UPDATE DOI SET username = 'Soham' WHERE user_id = '103';
UPDATE DOI SET username = 'Jagtap' WHERE user_id = '104';
UPDATE DOI SET username = 'Vritika' WHERE user_id = '105';
UPDATE DOI SET username = 'Sakshi' WHERE user_id = '106';
UPDATE DOI SET username = 'Rohan' WHERE user_id = '107';
UPDATE DOI SET username = 'Tanishka' WHERE user_id = '108';
UPDATE DOI SET username = 'Maitreyee' WHERE user_id = '109';
UPDATE DOI SET username = 'Vedant' WHERE user_id = '110';
UPDATE DOI SET username = 'Ishita' WHERE user_id = '111';
UPDATE DOI SET username = 'Saharsh' WHERE user_id = '112';
UPDATE DOI SET username = 'Sarakshie' WHERE user_id = '113';
UPDATE DOI SET username = 'Rakshit' WHERE user_id = '114';
UPDATE DOI SET username = 'Aditi' WHERE user_id = '115';
UPDATE DOI SET username = 'Jay' WHERE user_id = '116';
UPDATE DOI SET username = 'Aryan' WHERE user_id = '117';
UPDATE DOI SET username = 'Vanshika' WHERE user_id = '118';
UPDATE DOI SET username = 'Aarya' WHERE user_id = '119';
UPDATE DOI SET username = 'Ameya' WHERE user_id = '120';

Update DOI set DOR = NULL WHERE user_id = 106;
Update DOI set DOR = NULL WHERE user_id = 114;
Update DOI set DOR = NULL WHERE user_id = 115;
Update DOI set DOR = NULL WHERE user_id = 109;
DESC bookpeople;
ALTER TABLE bookpeople ADD UNIQUE (user_id);
SHOW CREATE TABLE bookpeople;
select COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_COLUMN_NAME, REFERENCED_TABLE_NAME 
from information_schema.KEY_COLUMN_USAGE where TABLE_NAME = 'book';
show create table bookpeople;
SELECT *
FROM user_cons_columns
WHERE table_name = 'bookpeople';
DESC bookpeople;
ALTER TABLE book ADD UNIQUE (book_id);
DESC book;
select * from DOI;
select branch, count(*) from bookpeople group by branch;
select * from bookpeople order by user_id;
SELECT A.username, B.username, A.branch from bookpeople A, bookpeople B where A.branch=B.branch and A.username<>B.username;
SELECT bookpeople.username, book.title, book.price FROM bookpeople, book WHERE bookpeople.book_id = book.book_id;
UPDATE bookpeople SET book_id = 'b107' where user_id = 102;
UPDATE bookpeople SET book_id = 'b102' where user_id = 105;
select * from bookpeople order by user_id;
SELECT bookpeople.username, book.title, book.price, bookpeople.book_id FROM bookpeople, book WHERE bookpeople.book_id BETWEEN 'b109' AND 'b110';
SELECT bookpeople.username ||'has the book'|| book.title ||'taken on'|| DOI.DOI NON_EQUI_JOIN FROM bookpeople, book, DOI WHERE (bookpeople.book_id=book.book_id) AND (bookpeople.book_id BETWEEN 'b109' AND 'b110');
SELECT username, address, title FROM bookpeople CROSS JOIN book WHERE user_id<104;
SELECT * FROM bookpeople NATURAL JOIN DOI;
SELECT * FROM bookpeople JOIN DOI using (user_id) where bookpeople.book_id = any(select book_id FROM bookpeople where DOR is not null);
SELECT * FROM bookpeople JOIN DOI using (user_id) WHERE bookpeople.book_id < any(SELECT 'b103' from book );
SELECT e.username, e.address, e.user_id, d.title, d.DOR FROM bookpeople e, DOI d where e.user_id = d.user_id(+);
SELECT e.username, e.address, e.user_id, d.title, d.DOR FROM bookpeople e, DOI d where e.user_id = d.user_id(+);
DELETE FROM DOI where user_id = 106; 
DELETE FROM DOI where user_id = 109; 
DELETE FROM DOI where user_id = 118; 
SELECT e.username, e.address, e.user_id, d.title, d.DOR FROM bookpeople e, DOI d where e.user_id = d.user_id(+);
SELECT e.user_id, e.username, e.address, d.title, d.DOR FROM bookpeople e LEFT JOIN DOI d on e.user_id = d.user_id;
SELECT a.user_id, a.username, a.branch, b.title, b.author FROM bookpeople a, book b WHERE a.book_id = b.book_id(+) AND b.book_id = (SELECT b.book_id FROM book WHERE author = 'Dan Brown'); 
SELECT e.user_id, e.username, e.address, d.title, d.DOR FROM bookpeople e LEFT JOIN DOI d on e.user_id = d.user_id AND e.user_id = ANY(SELECT e.user_id FROM bookpeople WHERE DOR IS null) ;
SELECT e.user_id, e.username, e.address, d.title, d.DOR FROM bookpeople e, DOI d WHERE e.user_id = d.user_id(+) AND e.book_id = ANY (SELECT e.book_id FROM book);
SELECT e.user_id, e.username, e.address, d.title, d.DOR FROM bookpeople e RIGHT JOIN DOI d ON e.user_id = d.user_id;
SELECT e.user_id, e.username, e.address, d.title, d.DOR FROM bookpeople e, DOI d WHERE e.user_id(+) = d.user_id;
SELECT * FROM DOI;
SELECT d.user_id, d.username, e.address, d.title, d.DOR FROM bookpeople e, DOI d WHERE e.user_id(+) = d.user_id;
INSERT INTO DOI (user_id, username) VALUES (121, 'Harsh');
INSERT INTO DOI (user_id, username, title) VALUES (122, 'Disha', 'Old Man and the Sea');
SELECT e.user_id, e.username, e.book_id, d.title, d.DOR FROM bookpeople e RIGHT OUTER JOIN DOI d ON e.user_id = d.user_id WHERE d.user_id > 115;
